services:
  service-user-pg:
    image: postgres:latest
    container_name: user-pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: service-user
    ports:
      - "5434:5432"
    volumes:
      - user_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  user_data:
