services:
  service-customer-pg:
    image: postgres:latest
    container_name: customer-pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: service-customer
    ports:
      - "5434:5432"
    volumes:
      - customer_data:/var/lib/postgresql/data
    restart: unless-stopped

  service-customer:
    build: ./service-customer
    container_name: service-customer
    depends_on:
      - service-customer-pg
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@service-customer-pg:5432/service-customer
    volumes:
      - ./service-customer:/app
    restart: unless-stopped

  service-reservation-pg:
    image: postgres:latest
    container_name: reservation-pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: service-reservation
    ports:
      - "5433:5432"
    volumes:
      - reservation_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  service-reservation:
    build: ./service-reservation
    container_name: service-reservation
    depends_on:
      - service-reservation-pg
    ports:
      - "5001:5000"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://service-reservation-pg:5432/service-reservation
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SERVER_PORT=5000
      - SERVICE_CUSTOMER_URL=http://service-customer:5000
    restart: unless-stopped

volumes:
  customer_data:
  reservation_postgres_data:
