services:
  service-customer-pg:
    image: postgres:latest
    container_name: local_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: service-customer
    ports:
      - "5432:5432"
    volumes:
      - customer_data:/var/lib/postgresql/data
    restart: unless-stopped

  service-customer-redis:
    image: redis:latest
    container_name: local_redis
    ports:
      - "6379:6379"
    volumes:
      - customer_redis_data:/data
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning

  service-reservation-pg:
    image: postgres:latest
    container_name: reservation_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: service-reservation
    ports:
      - "5433:5432"
    volumes:
      - reservation_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  service-reservation-redis:
    image: redis:latest
    container_name: reservation_redis
    ports:
      - "6380:6379"
    volumes:
      - reservation_redis_data:/data
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning

volumes:
  customer_data:
  customer_redis_data:
  reservation_postgres_data:
  reservation_redis_data:
