services:
  service-room-pg:
    image: postgres:latest
    container_name: room-pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: service-room
    ports:
      - "5434:5432"
    volumes:
      - room_data:/var/lib/postgresql/data
    restart: unless-stopped
  service-room-redis:
    image: redis:latest
    container_name: room-redis
    ports:
      - "6380:6379"
    volumes:
      - room_redis_data:/data
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning

volumes:
  room_data:
  room_redis_data:
